name: Merge Release Branch
on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Full name of the release branch to merge (e.g., release/0.1.0)'
        required: true

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Merge into Main
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git merge --no-ff origin/${{ github.event.inputs.release_branch }}
          git push origin main

      - name: Tag the Release
        run: |
          # Extract version from the release branch name (e.g., release/0.1.0 -> 0.1.0)
          VERSION=$(echo "${{ github.event.inputs.release_branch }}" | sed 's|release/||')
          git tag -a "v$VERSION" -m "Release $VERSION"
          git push origin --tags

      - name: Merge into Develop
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff origin/${{ github.event.inputs.release_branch }}
          git push origin develop