name: PR Checks

on:
  push:
    branches-ignore:
      - feature/deploy-to-gh-pages # TODO: change to main

jobs:
  lint:
    name: Linting and Prettier Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: ./.github/actions/cache-node-modules

      - name: Cache Cypress Binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Node Modules
        uses: ./.github/actions/cache-node-modules

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Application
        run: npm run build

      - name: Save Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Needed for Cypress to access configuration file from repo
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Restore Node Modules
        uses: ./.github/actions/cache-node-modules

      - name: Restore Cypress Binary Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Serve the Application
        run: nohup npm run preview -- --port 5173 &
        env:
          CI: true

      - name: Wait for server to be ready
        run: npx wait-on http://ip6-localhost:5173/github-actions-example
        timeout-minutes: 1

      - name: Run Cypress Tests
        run: npx cypress run